import { useLayoutEffect } from 'react'

type SeoParams = {
  title: string
  description: string
  url?: string
  image?: string
  canonicalPath?: string
  keywords?: string
  structuredData?: any | any[]
}

function upsertMetaTag(attrName: string, attrValue: string, content: string) {
  const el = document.querySelector(`meta[${attrName}="${attrValue}"]`) as HTMLMetaElement | null
  if (el) {
    el.content = content
    return
  }

  const meta = document.createElement('meta')
  meta.setAttribute(attrName, attrValue)
  meta.setAttribute('content', content)
  document.head.appendChild(meta)
}

function upsertLinkTag(rel: string, href: string) {
  let el = document.querySelector(`link[rel="${rel}"]`) as HTMLLinkElement | null
  if (!el) {
    el = document.createElement('link')
    el.setAttribute('rel', rel)
    document.head.appendChild(el)
  }
  el.setAttribute('href', href)
}

function upsertJsonLd(structuredData: any | any[], id = 'ld-json') {
  try {
    // Remove any previously injected JSON-LD generated by this hook
    const prev = document.querySelectorAll('script[type="application/ld+json"][data-generated-by="useSeo"]')
    prev.forEach((p) => p.remove())

    if (!structuredData) return

    const script = document.createElement('script')
    script.setAttribute('type', 'application/ld+json')
    script.setAttribute('data-generated-by', 'useSeo')
    script.setAttribute('data-jsonld-id', id)

    const payload = Array.isArray(structuredData) ? structuredData : [structuredData]
    script.textContent = JSON.stringify(payload.length === 1 ? payload[0] : payload, null, 2)
    document.head.appendChild(script)
  } catch (err) {
    // Fail silently — structured data injection should not break the app
    // eslint-disable-next-line no-console
    console.warn('Failed to inject JSON-LD', err)
  }
}

function normalizeNonEmpty(value: string, fallback: string) {
  const trimmed = value?.trim()
  return trimmed && trimmed.length > 0 ? trimmed : fallback
}

export default function useSeo({
  title,
  description,
  url,
  image,
  canonicalPath,
  keywords,
  structuredData,
}: SeoParams) {
  useLayoutEffect(() => {
    const finalUrl = url ?? (canonicalPath ? new URL(canonicalPath, window.location.origin).toString() : window.location.href)

    // Ensure non-empty values to avoid SEO “empty title/description/H1” mismatches.
    const safeTitle = normalizeNonEmpty(title, 'Wild Path | Tailor-Made Travel Experiences in Costa Rica')
    const safeDescription = normalizeNonEmpty(
      description,
      'Wild Path offers tailor-made travel in Costa Rica — private wildlife, waterfall & cloud forest tours in Bajos del Toro.'
    )

    document.title = safeTitle

    // Standard description
    upsertMetaTag('name', 'description', safeDescription)

    // Keywords (optional, but cheap)
    if (keywords && keywords.trim().length > 0) {
      upsertMetaTag('name', 'keywords', keywords)
    }

    // Canonical
    if (finalUrl) {
      upsertLinkTag('canonical', finalUrl)
    }

    // Open Graph
    upsertMetaTag('property', 'og:title', safeTitle)
    upsertMetaTag('property', 'og:description', safeDescription)
    if (image) upsertMetaTag('property', 'og:image', image)
    if (finalUrl) upsertMetaTag('property', 'og:url', finalUrl)
    upsertMetaTag('property', 'og:type', 'website')

    // Twitter
    upsertMetaTag('name', 'twitter:title', safeTitle)
    upsertMetaTag('name', 'twitter:description', safeDescription)
    if (image) upsertMetaTag('name', 'twitter:image', image)
    upsertMetaTag('name', 'twitter:card', 'summary_large_image')

    // Inject structured data (JSON-LD)
    if (structuredData) {
      // Use canonicalPath or finalUrl to create a stable id
      const id = canonicalPath ? `ld-${canonicalPath.replace(/[^a-z0-9\-]/gi, '-')}` : 'ld-json'
      upsertJsonLd(structuredData, id)
    }
  }, [title, description, url, image, canonicalPath, keywords, structuredData])
}
